Task_1_1_1
Intelix8996/OOP pull request #1
Opened 2022-09-12 16:13 UTC by Intelix8996

Implement HeapSort

2022-09-13 08:34 UTC, Leidenn2509 submitted a review, later dismissed
- Удалите папку `.idea` в корне репозитория когда будете писать следующую лабу

2022-09-13 08:34 UTC, Leidenn2509 commented on Task_1_1_1/src/main/java/ru/nsu/nrepin/BinaryHeap.java
> +    private int[] array;
Обычно javadoc не пишут для приватных методов/полей. Только если там совсем что-то сложно

2022-09-13 08:34 UTC, Leidenn2509 commented on Task_1_1_1/src/main/java/ru/nsu/nrepin/BinaryHeap.java
> +    public BinaryHeap(int[] array) {
Я бы подвинул конструкторы вверх, после полей. Обычно структура класса следующая (поля, конструкторы/статические методы, методы). Это не обязательно, но чаще всего так удобнее читать код, так как первое что хочется знать о классе это то как его создать.

2022-09-13 08:37 UTC, Leidenn2509 commented
Ещё нужно залить скрипт для сборки

2022-09-13 08:38 UTC, Leidenn2509 requested changes
Ещё нужно залить скрипт для сборки

2022-09-13 11:07 UTC, Intelix8996 commented on Task_1_1_1/src/main/java/ru/nsu/nrepin/BinaryHeap.java
> +    public BinaryHeap(int[] array) {
Исправил

2022-09-14 09:20 UTC, alradish approved these changes

2022-09-14 09:20 UTC, merged