Task_2_2_1
Intelix8996/OOP pull request #10
Opened 2023-03-13 15:37 UTC by Intelix8996

2023-03-13 15:37 UTC, Intelix8996 commented
Soft deadline

2023-03-31 18:04 UTC, alradish requested changes

2023-03-31 18:04 UTC, alradish commented on Task_2_2_1/src/main/java/ru/nsu/nrepin/Storage.java
> +    private final Stack<Integer> storage;
Лучше наверное всё же Queue

2023-03-31 18:04 UTC, alradish commented on Task_2_2_1/src/main/java/ru/nsu/nrepin/Storage.java
> +        if (storage.size() == capacity) {
Надо блокироваться и ждать пока не освободится место

2023-03-31 18:04 UTC, alradish commented on Task_2_2_1/src/main/java/ru/nsu/nrepin/Baker.java
> +                synchronized (orderQueue) {
Блокировки надо перенести в сторадж

2023-03-31 18:04 UTC, alradish commented on Task_2_2_1/src/main/java/ru/nsu/nrepin/OrderRegistry.java
> +        registry.put(id, false);
Синхронизация

2023-03-31 18:04 UTC, alradish commented on Task_2_2_1/src/main/java/ru/nsu/nrepin/Main.java
> +public class Main {
Это всё пицерия, а не `Main`

2023-04-09 08:17 UTC, alradish requested changes

2023-04-09 08:17 UTC, alradish commented on Task_2_2_1/src/main/java/ru/nsu/nrepin/Baker.java
> +    private final BlockingQueue<Integer> orderQueue;
Суть задачи написать блокирующуюся коллекцию. Мы обсуждали, что использовать коллекции из конкурента нельзя

2023-04-09 08:17 UTC, alradish commented on Task_2_2_1/src/main/java/ru/nsu/nrepin/Pizzeria.java
> +    public static void main(String[] args) {
Функция мейн не должна быть частью вашей модели. Код из этого мейна это логика работы пиццерии. Мейн должен только его запускать

2023-06-20 09:17 UTC, alradish approved these changes

2023-06-20 09:17 UTC, merged