Task_2_3_1
Intelix8996/OOP pull request #11
Opened 2023-04-14 11:12 UTC by Intelix8996

2023-04-14 11:12 UTC, Intelix8996 commented
Soft deadline

2023-05-16 08:44 UTC, alradish requested changes
- Нужно выделить пакеты. Как минимум model, чтобы отделить её от гуи

2023-05-16 08:44 UTC, alradish commented on Task_2_3_1/src/main/java/ru/nsu/nrepin/Cell.java
> +public enum Cell {
Стены бы ещё

2023-05-16 08:44 UTC, alradish commented on Task_2_3_1/src/main/java/ru/nsu/nrepin/Snake.java
> +        tailPositions.add(new Vector2(5, 8));
- В начале змейка без хвоста
- Да и что за магические числа такие

2023-05-16 08:44 UTC, alradish commented on Task_2_3_1/src/main/java/ru/nsu/nrepin/GameModel.java
> +    private final GameView gameView;
Модель не должна содержать fx

2023-05-23 08:00 UTC, alradish requested changes
- T food
- score/goal

2023-05-23 08:28 UTC, alradish approved these changes

2023-05-23 08:28 UTC, merged