Task_1_2_2
Intelix8996/OOP pull request #3
Opened 2022-10-08 10:07 UTC by Intelix8996

2022-10-11 14:44 UTC, Leidenn2509 requested changes
- Добавьте возможность получить родителя

2022-10-11 14:44 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/nrepin/Tree.java
> +    private List<Tree<T>> traverseDepthFirst() {
Перепишите итеративно

2022-10-11 14:44 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/nrepin/Tree.java
> +    public void prettyPrint() {
Лучше выдайте строку, а где нужно распечтайте.
Это пригодится, например, если бы вам потребовалось загнать ваше дерево файл

2022-10-11 14:44 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/nrepin/Tree.java
> +    public void prettyPrint() {
Используйте `StringBuilder` для этого

2022-10-11 14:44 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/nrepin/Tree.java
> +        List<Tree<T>> searchResult = traverseTree(type);
Итерироваться через всё дерево ещё даже до создания итератора не очень хорошая идея. Нужно, чтобы это делал итератор, и только столько, сколько нужно.

2022-10-11 14:44 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/nrepin/Tree.java
> +            throw new ConcurrentModificationException();
Должен бросать итератор

2022-10-11 14:44 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/nrepin/Tree.java
> +    public Tree<T> add(Tree<T> node, T newElem) {
`static`?

2022-10-11 14:44 UTC, Leidenn2509 commented on Task_1_2_2/src/test/java/ru/nsu/nrepin/TreeTests.java
> +        refBreadthFirst = List.of(1, 2, 3, 4, 5, 7, 8, 9, 13, 14, 10, 11, 12, 6);
Если они не меняются, то лучше запихать их в константы, чтобы не пересоздавать каждый раз

2022-10-11 15:12 UTC, Intelix8996 commented on Task_1_2_2/src/main/java/ru/nsu/nrepin/Tree.java
> +    public Tree<T> add(Tree<T> node, T newElem) {
Там вроде как по условию этот метод должен вызываться с объекта. Если сделать его статическим, тогда возникает вопрос: Допускается ли вызывать статические методы с объектов?  Если так сделать, то генерируется warning.

2022-10-11 15:39 UTC, Intelix8996 commented on Task_1_2_2/src/main/java/ru/nsu/nrepin/Tree.java
> +            throw new ConcurrentModificationException();
То есть, когда вызываем next() у итератора?

2022-10-14 07:30 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/nrepin/TreeIterator.java
> +public class TreeIterator<T> implements Iterator<T> {
Сейчас сойдёт. Но в будущем я бы советовал такие классы(где в каждом методе есть свитч) просто разделить на два разных класса, а свитч вынести наверх(в данном случае в `Tree.iterator`.

2022-10-14 07:30 UTC, Leidenn2509 commented on Task_1_2_2/src/main/java/ru/nsu/nrepin/Tree.java
> +    public Tree<T> add(Tree<T> node, T newElem) {
А. Я понял о чём вы. Пример либо плохой, либо я что-то не понял. Оставьте статик, так как этот метод действительно не использует состояние текущей ноды.

2022-10-14 07:30 UTC, alradish approved these changes

2022-10-14 07:31 UTC, merged