Task_1_4_1
Intelix8996/OOP pull request #6
Opened 2022-11-23 13:37 UTC by Intelix8996

2022-12-06 12:44 UTC, alradish requested changes

2022-12-06 12:44 UTC, alradish commented on Task_1_4_1/src/main/java/ru/nsu/nrepin/RecordBook.java
> +    public enum Grade {
Лучше вынести в отдельный класс

2022-12-06 12:44 UTC, alradish commented on Task_1_4_1/src/main/java/ru/nsu/nrepin/RecordBook.java
> +        Grade(int intValue) {
public

2022-12-06 16:11 UTC, Intelix8996 commented on Task_1_4_1/src/main/java/ru/nsu/nrepin/RecordBook.java
> +        Grade(int intValue) {
Конструктор enum'а нельзя сделать публичным, он может быть только private, поэтому, ключевое слово опускают.

2022-12-17 13:14 UTC, alradish approved these changes

2022-12-17 13:15 UTC, merged