Implement Task_2_1_1
Intelix8996/OOP pull request #9
Opened 2023-02-11 20:10 UTC by Intelix8996

2023-02-11 20:11 UTC, Intelix8996 commented
Soft deadline

2023-02-14 15:35 UTC, alradish requested changes

2023-02-14 15:35 UTC, alradish commented on Task_2_1_1/src/main/java/ru/nsu/nrepin/PrimeCheckerThread.java
> +public class PrimeCheckerThread extends Thread {
Один из `ThreadPrimeChecker` & `PrimeCheckerThread` придется переименовать

2023-02-27 05:29 UTC, alradish approved these changes

2023-02-27 05:29 UTC, merged